---
title: "get morning data"
author: "Erich Neuwirth"
date: '2022-02-28'
output: html_document
---

Die neue Datei beginnt 2020-03-01
Wir binden die früheren Daten aus einer zusätzlichen Datei dazu.

Die Daten von 2021-11-14 fehlen, die werden interpoliert.


```{r setup, echo=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE
) 
```


```{r}
interpolate <- TRUE
```

```{r}
suppressPackageStartupMessages({
  library(here)
  library(fs)
})  
source(path(here(),"utils","purl_and_source.R"))
purl_and_source(path(here(),"utils","base_utils.Rmd"))
```

```{r}
remove_data <- TRUE
```


```{r}
purl_and_source(path(here(),"utils","get_data_utils.Rmd"))
```

```{r}
save_path <- path(here(),"data","raw_data")
```

```{r}
suppressMessages(
read_csv2(
  "https://info.gesundheitsministerium.gv.at/data/timeline-faelle-ems.csv")) |>
  mutate(Datum=as.Date(Datum)) |>
  rename(Bundesland=Name) |>
  rename(cases_EMS=BestaetigteFaelleEMS) |>
  mutate_if(is.numeric,as.integer)  ->
  ems_morning_data_raw  
```



```{r}
if (interpolate) {
  ems_morning_data_raw |>
    filter(Datum %in% (as.Date("2021-11-13") + c(0,2))) |>
    mutate_at(vars(cases_EMS),log) |>
    group_by(Bundesland,BundeslandID) |>
    summarise(cases_EMS=round(exp(mean(cases_EMS)))) |>
    ungroup() |>
    mutate(cases_EMS=ifelse(BundeslandID==10,
                  sum(cases_EMS)-cases_EMS,
                  cases_EMS)) |>
    arrange(BundeslandID) |>
    mutate(Datum=as.Date("2021-11-14"),.before=1)
} ->
  ems_20211114
```
```{r}
ems_morning_data_raw |>
  bind_rows(ems_20211114) |>
  arrange(Datum,BundeslandID) |>
  mutate_if(is.numeric,as.integer) ->
  ems_morning_data_raw
```


```{r}
load(path(
  here(),"data","old_data",
  "ems_bmi_data_upto_feb21.RData"
))
```

```{r}
ems_morning_data_raw |>
  pull(Datum) |>
  min() ->
  first_date_new_file
```


```{r}
ems_bmi_data_upto_feb21 |>
  filter(Datum < first_date_new_file) |>
  select(Datum:cases_EMS) |>
  mutate(Datum=as.Date(Datum)) |>
  mutate_if(is.numeric,as.integer) |>
  bind_rows(ems_morning_data_raw |>
              mutate(Datum=as.Date(Datum))) ->
  ems_morning_data 
```

```{r}
check_for_holes(ems_morning_data$Datum)
```


```{r}
save(ems_morning_data,
     file=path(save_path,"ems_morning_data.RData"))
```

```{r}
if(exists("remove_data")){
if(remove_data){
  remove(ems_bmi_data_upto_feb21,
         ems_morning_data,
         ems_morning_data_raw,
         bundesland_permanent_df)
  remove(remove_data)
}}
```

