---
title: "get owid data"
author: "Erich Neuwirth"
date: '2022-03-01'
output: html_document
---




```{r setup, echo=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE
) 
```

```{r}
suppressPackageStartupMessages({
  library(here)
  library(fs)
  library(readxl)
})  
source(path(here(),"utils","purl_and_source.R"))
purl_and_source(path(here(),"utils","base_utils.Rmd"))
```

```{r}
remove_data <- TRUE
```


```{r}
purl_and_source(path(here(),"utils","get_data_utils.Rmd"))
```

```{r}
save_path <- path(here(),"data","raw_data")
```


```{r}
#read_excel(path(here(),"data","old_data",
#                "Laender_Namen.xlsx")) ->
#  laender_namen
```

```{r}
load(path(here(),"data","old_data",
                 "country_names_data.RData"))
```


```{r}
read_carefully(
  "https://covid.ourworldindata.org/data/owid-covid-data.csv") |>
#  left_join(
#    laender_namen |>
#      select(Land,alpha_3) |>
#      rename(iso_code=alpha_3)
#  ) |>
  left_join(country_names_data) |>
  select(iso_code:location,country,Land,everything()) ->
  owid_data
```

```{r}
#owid_data |>
#  select(iso_code,location,Land) |>
#  distinct() |>
#  rename(country=location) ->
#  country_names_data
#save(country_names_data,
#     file=path(here(),"data","old_data",
#              "country_names_data.Rdata")) 
```


```{r}
save(owid_data,
     file=path(save_path,"owid_data.RData"))
```

```{r}
openxlsx::write.xlsx(owid_data,
                     path(here(), "data", "xlsx_to_work",
                          "owid_data.xlsx"))
```

```{r}
owid_data |>
  names() #|>
#  keep(\(x)str_detect(x,"total"))
```  
```{r}
owid_data |> 
  select(date,Land,total_cases,population,
         total_deaths_per_million,
         total_tests_per_thousand,
         people_fully_vaccinated_per_hundred,
         total_boosters_per_hundred) |>
  filter(total_cases > 10) |>
  group_by(Land)  |>
  summarise_all(\(x)max(x,na.rm = TRUE)) |>
  ungroup() |>
  mutate(Anteil=total_cases/population) |>
  mutate_at(vars(-Land),(\(x)ifelse(is.finite(x),x,NA))) |>
  filter(!is.na(total_cases)) |>
  filter(!is.na(population)) |>
  rename(Datum=date,
         Fälle=total_cases,
         Einwohner=population,
         Tote_per_Mio=total_deaths_per_million,
         Tests_pro_Tsd=total_tests_per_thousand,
         Geimpft_2x=people_fully_vaccinated_per_hundred,
         Geimpft_3x=total_boosters_per_hundred,
         Anteil_Positiv=Anteil) |>
  mutate_at(vars(Geimpft_2x,Geimpft_3x),\(x)x/100) |>
  mutate_at(vars(Tote_per_Mio,Tests_pro_Tsd),round) |>
  arrange(desc(Anteil_Positiv)) |>
  select(-Datum) ->
  wb_data
#  clipr::write_clip()
 class(wb_data$Geimpft_2x) <- "percentage"
 class(wb_data$Geimpft_3x) <- "percentage"
 class(wb_data$Anteil_Positiv) <- "percentage"
wb <- createWorkbook()
sheet <- "COVID_Kennzahlen"
addWorksheet(wb = wb, sheet = sheet)
addStyle(wb = wb, sheet = sheet, 
         style = createStyle(numFmt = "NUMBER"), 
         rows = 2:1000, cols = 2)

  openxlsx::write.xlsx(wb_data,
                      file=
                        path(here(),"COVID_current_state.xlsx"))
```


```{r}
if(exists("remove_data")){
if(remove_data){
remove(owid_data,
   country_names_data,
   bundesland_permanent_df,
   remove_data)
}}  
```

