---
title: "Tests"
author: "Erich Neuwirth"
date: "`r Sys.Date()`"
output:
  pdf_document:
    includes:
      in_header: mystyles.sty
    toc: yes
    toc_depth: 2
  html_document:
    toc: yes
    toc_depth: '2'
    df_print: paged
fontsize: 12pt
keep_md: true
---

```{r}
library(tidyverse)
```


```{r, echo=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, message = FALSE,
  warning = FALSE, comment = NULL
)
```

```{r, echo=FALSE}
output_format <- function(){
  knitr::opts_knit$get("rmarkdown.pandoc.to")
}
```



Output to `r output_format()`


```{r, results="asis"}
#if(output_format() == "latex") 
#  cat("\\DraftwatermarkOptions{final}")
```

```{r, echo=FALSE}
pagebreak <- function(){
  if (output_format() == "latex") return("\\pagebreak\n")
  if (output_format() == "html") {
  return(paste(
    '<p style="page-break-after: always;">&nbsp;</p>\n',
    '<p style="page-break-before: always;">&nbsp;</p>\n'
  ))
  }
}
```

```{r}
leerzeile <- function(lines=1){
    if (output_format() == "latex") 
      return(
          paste0("\n\\vspace{",
                  lines*12,
                     "pt}\n")
      )
  if(output_format()=="html")
    return(paste(rep("<br>",lines),collapse=" "))
}
```

# Erstes

Zeile 1


Zeile 2


`r leerzeile()`

Zeile 3

`r leerzeile(2)`

Zeile 4



## Erstes Unter

## Zweites Unter

```{r, fig.align="center",fig.width=4}
my_df <- tibble(
  x=seq(0,1,0.5),
  y=x^2
)
my_df |>
  ggplot(aes(x=x,y=y)) +
  geom_line() +
  theme_minimal()
```


# Zweites

## Erstes Unter

`r pagebreak()`


## Zweites Unter

