---
title: "facetscales test"
output: html_document
date: '2022-05-11'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
set.seed(123456)
test_df <-
  tibble(t=1:10,
         x=100+runif(10,-10,10),
         y=10+runif(10,-4,4),
         p=y/x)

test_df |>
  pivot_longer(cols=x:p,
               names_to = "var",
               values_to = "value") |>
  mutate(var=factor(var,levels=c("x","y","p"))) ->
  test_df_long

test_df_long |>
  ggplot(aes(x=t,y=value)) +
  geom_line() +
  scale_y_continuous(limits=c(0,NA)) +
  facet_wrap(vars(var),ncol=1,
             scales = "free_y") +
  ggh4x::facetted_pos_scales(
    y = var == "p" ~ scale_y_continuous(
      labels = percent,
      limit=c(0,NA)
  ))
```

```{r}
library(facetscales)



scales_y <- list(
  x = scale_y_continuous(),
  y = scale_y_continuous(),
  p = scale_y_continuous(labels = percent_format())
)

test_df_long |>
  ggplot(aes(x=t,y=value)) +
  geom_line() +
  scale_y_continuous(limits=c(0,NA)) +
  facet_grid_sc(rows = vars(var), scales = list(y = scales_y))
```

