---
title: "Wöchentlich"
output: html_document
date: '2022-04-11'
---




  
```{r local_setup_inc, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, message = FALSE,
  warning = FALSE, comment = NULL
)
options(scipen = 999)
options(OutDec = ",")
options(decimal.mark = ",")
```


```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(magrittr)
  library(fs)
  library(here)
  library(ggiraph)
  library(scales)
  library(gt)
  library(ggmosaic)
  library(htmlwidgets)
  library(cowplot)
  library(clipr)
  library(openxlsx)
  library(ggiraph)
})
```


```{r}
source(path(here(), "utils", "purl_and_source.R"))
purl_and_source(path(here(), "utils", "base_utils.Rmd"))
purl_and_source(path(here(), "utils", "date_utils.Rmd"))
```


```{r}
theme_set(theme_date_vert())
```

```{r}
purl_and_source(
  path(
    here(), "utils", "get_data",
    "get_bmsgpk_data.Rmd"
  )
)
```

```{r}
load(path(here(),"data","raw_data",
          "bmi_data.RData"))
```


```{r}
purl_and_source(
  path(
    here(), "utils", "get_data",
    "get_ages_data.Rmd"
  )
)
```


```{r}
load(path(here(),"data","raw_data",
          "ages_data.RData"))
```

```{r}
bmi_data |>
  names()
```

```{r}
bmi_data |>
  mutate(Datum=as.Date(Datum)) |>
  filter(Datum >= (Sys.Date() - 6*7)) |>
  group_by(Bundesland,BundeslandID) |>
  mutate(cases_weekly=cases_BMI-lag(cases_BMI,7),
         tests_weekly=Tests_PCR_BMI-
           lag(Tests_PCR_BMI,7)) |>
  mutate(cases_rate=cases_weekly/lag(cases_weekly,7)) |>
  mutate(tests_rate=tests_weekly/lag(tests_weekly,7)) |>
  ungroup() ->
  rates
```

```{r}
signed_percent <- function(x,accuracy=1){
  res <- percent(x,accuracy=accuracy,decimal.mark = ",") 
  if (x > 0) res <- paste0("+",res)
  if (x == 0) res <- paste0("±",res)
  res
}
```


```{r}
rates |>
  filter(BundeslandID==10) |>
  drop_na() |>
  select(Datum,ends_with("rate")) |>
  rename(Fälle=cases_rate,
         Tests=tests_rate) |>
  pivot_longer(cols = Fälle:Tests,
               names_to = "Veränderung",
               values_to = "values") |>
  mutate(values=values-1) |>
  ggplot(aes(x=Datum,y=values,color=Veränderung)) +
  geom_line() +
  geom_hline(yintercept = 0, linetype="dotted") +
  scale_y_continuous("Veränderung",
                     labels = signed_percent) +
  scale_color_discrete("") +
  scale_x_date(labels = ger_date_1_Jan) +
  labs(title="Fallzahlen und Tests pro Woche (Vergleich zur Vorwoche)") +
  theme(axis.text.x = element_blank(),
        legend.position = "top") ->
  chart_1
```
```{r}
rates |>
  mutate(pos_rate=cases_weekly/tests_weekly) |>
  filter(BundeslandID==10) |>
  drop_na() |>
  ggplot(aes(x=Datum,y=pos_rate)) +
  geom_line() +
  scale_y_continuous("Positivitätsrate",
                     labels = \(x)percent(x,accuracy=1),
                     breaks=seq(0,0.2,by=0.02), 
                     limits=c(0,NA)) +
  scale_x_date(labels = ger_date_1_Jan)->
  chart_2
  
```


```{r}
library(cowplot)
```

```{r}
plot_grid(chart_1,chart_2,nrow=2)
```

### Heldenplatz Konzert



```{r}
ages_data |>
  names()
```


```{r}
heldenplatz_konzert_datum <- as.Date("2022-03-25")
happelstadion_konzert_datum <- as.Date("2022-03-19")
```


```{r}
ages_data |> 
  filter(Datum >= (happelstadion_konzert_datum-3*7)) |>
  select(Datum,BundeslandID,Bundesland,
         cases_7_AGES
         ) |>
  left_join(pop_austria |>
              select(BundeslandID,Bundesland,pop)) |>
  mutate(Inzidenz=100000*cases_7_AGES/pop) ->
  konzert_data
```


```{r}
konzert_data |>
  filter(BundeslandID==10) |>
  ggplot(aes(x=Datum,y=Inzidenz)) +
  geom_line() +
  geom_vline(xintercept = heldenplatz_konzert_datum,
             linetype = "dashed") +
  geom_vline(xintercept = happelstadion_konzert_datum,
             linetype = "dashed")
```


```{r}
bl_pal <-
  gg_color_hue(10)
names(bl_pal) <- 
  pop_austria |>
  slice(-1) |>
  pull(Bundesland) 
bl_pal["Österreich"] <- "black" 
bl_pal["Wien"] <- "red"
```


```{r}
konzert_data |>
  filter(Datum==max(Datum)) |>
  select(Bundesland,Inzidenz) |>
  arrange(desc(Inzidenz)) |>
  pull(Bundesland) ->
  bl_order
```
```{r}
bl_pal <-
  bl_pal[bl_order]
```

```{r}
linesize_pal <- c(wide=1.5,narrow=0.5)
konzert_data |>
  mutate(Bundesland=factor(Bundesland,
                           levels=bl_order)) |>
  mutate(linesize=ifelse(BundeslandID %in% 9:10,
                          "wide", "narrow")) |>
#  filter(BundeslandID==10) |>
  ggplot(aes(x=Datum,y=Inzidenz,color=Bundesland,
             size=linesize)) +
  geom_line() +
  geom_vline(xintercept = heldenplatz_konzert_datum,
             linetype = "dashed") +
  geom_vline(xintercept = happelstadion_konzert_datum,
             linetype = "dashed")  +
  geom_text(x=heldenplatz_konzert_datum-0.75,y=1700,
            label="Heldenplatz-Konzert",
            size=3.5,angle=90,
            inherit.aes = FALSE) +
  geom_text(x=happelstadion_konzert_datum-0.75,y=1700,
            label="Happelstadion-Konzert",
            size=3.5,angle=90,
            inherit.aes = FALSE) +  
  scale_size_manual(values=linesize_pal) +
  scale_color_manual(values=bl_pal) +
  guides(size="none")
```